import os
import smtplib
import time
import schedule
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta, timezone
from dotenv import load_dotenv
from app.database import SessionLocal
from app.models import Article, User 

load_dotenv()

SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")

def generate_newsletter_html(articles):
    """Wraps the AI summaries in a clean HTML template."""
    html_content = """
    <html>
      <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <h2 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
          🚀 Your Daily Tech Intelligence
        </h2>
    """
    
    for article in articles:
        formatted_summary = article.ai_summary.replace('\n', '<br>')
        
        html_content += f"""
        <div style="margin-bottom: 25px; padding: 15px; background-color: #f9f9f9; border-radius: 8px;">
            <a href="{article.link}" style="text-decoration: none; color: #2980b9;">
                <h3 style="margin-top: 0;">{article.title}</h3>
            </a>
            <div style="font-size: 14px; line-height: 1.6;">
                {formatted_summary}
            </div>
        </div>
        """
        
    html_content += """
        <p style="text-align: center; font-size: 12px; color: #7f8c8d; margin-top: 30px;">
          Generated by your custom AI Agent.
        </p>
      </body>
    </html>
    """
    return html_content

def send_newsletter():
    db = SessionLocal()
    print("\n📬 [07:00 AM Trigger] Preparing today's newsletter...")

    # 1. Fetch Today's Summarized Articles
    cutoff = datetime.now(timezone.utc) - timedelta(hours=24)
    todays_articles = db.query(Article).filter(
        Article.published_at > cutoff,
        Article.ai_summary != None
    ).order_by(Article.published_at.desc()).limit(5).all()

    if not todays_articles:
        print("📭 No new articles to send today.")
        db.close()
        return

    # 2. Fetch All Subscribed Users
    users = db.query(User).all()
    
    if not users:
        print("📭 No users found in the database. Add a user via the Streamlit app!")
        db.close()
        return

    print(f"👥 Found {len(users)} subscribers. Generating email payload...")
    html_body = generate_newsletter_html(todays_articles)

    # 3. Connect to the Gmail Server
    try:
        print("🚀 Connecting to Gmail server...")
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(SENDER_EMAIL, SENDER_PASSWORD)

        # 4. Loop through users and send customized emails
        for user in users:
            print(f"  -> Sending to {user.email}...")
            
            # Convert their saved string (e.g., "Fireship,Wired") into a Python list
            user_prefs = user.preferences.split(",") if user.preferences else []
            
            # Filter today's articles to ONLY include the ones this user wants
            custom_articles = [
                article for article in todays_articles 
                if str(article.source_id) in user_prefs
            ]
            
            # If they didn't select any feeds that had news today, skip them!
            if not custom_articles:
                print(f"Skipping {user.email} - no news matching their preferences today.")
                continue

            # Generate HTML with only THEIR chosen articles
            html_body = generate_newsletter_html(custom_articles)
            
            msg = MIMEMultipart("alternative")
            msg["Subject"] = f"AI Tech News - {datetime.now().strftime('%b %d')}"
            msg["From"] = SENDER_EMAIL
            msg["To"] = user.email
            msg.attach(MIMEText(html_body, "html"))

            server.send_message(msg)
            time.sleep(1)

        server.quit()
        print("✅ All newsletters successfully delivered!")

    except Exception as e:
        print(f"❌ Failed to send emails: {e}")
    finally:
        db.close()


# --- THE AUTOMATION ENGINE ---
if __name__ == "__main__":
    send_newsletter()